<?php

return array(
    '' => 'site/index',
    'primary-info' => 'register/FirstStep',
    'location-background' => 'register/SecondStep',
    'lifestyle-appearence' => 'register/ThirdStep',
    'education-career' => 'register/FourthStep',
    'upgrade-plan' => 'register/FifthStep',
    'login' => 'site/login',
    'forgot-password' => 'ForgotPassword/index',
    'profile-details' => 'Partner/Partnerdetails/userid',
    'edit-profile' => 'profile/EditProfile',
    'my-profile' => 'profile/MyProfile',
    'hobbies-interest' => 'profile/HobbiesInterest',
    'partner-preference' => 'profile/PartnerPreference',
    'my-account' => 'Myaccount/Index',
    'photo-album' => 'Profile/MyPhotos',
    'photo-settings' => 'Profile/PhotoSettings',
    'edit-contacts' => 'settings/editcontact',
    'edit-password' => 'settings/changepassword',
    'edit-address' => 'settings/changeaddress',
    'settings' => 'settings/index',
    'profile-visitors' => 'Myaccount/ProfileVisitors',
    'profile-visited' => 'Myaccount/ProfileVisited',
    'my-matches' => 'Matches/MyMatches',
    '2-way-matches' => 'Matches/TwoWayMatches',
    'looking-for-Me' => 'Matches/LookingMe',
    'contact-filters' => 'settings/ContactFilters',
    'email-sms-alert' => 'settings/MailSmsAlert',
    '<controller:\w+>/<id:\d+>' => '<controller>/view',
    '<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
    '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
);

