<?php
/* @var $this UserDetailsController */
/* @var $model UserDetails */

$this->breadcrumbs=array(
	'User Details'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'List UserDetails', 'url'=>array('index')),
	array('label'=>'Create UserDetails', 'url'=>array('create')),
	array('label'=>'Update UserDetails', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete UserDetails', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage UserDetails', 'url'=>array('admin')),
);
?>

<h1>View UserDetails #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'user_id',
		'email',
		'password',
		'contact_number',
		'profile_for',
		'first_name',
		'last_name',
		'gender',
		'dob_day',
		'dob_month',
		'dob_year',
		'religion',
		'caste',
		'sub_caste',
		'nakshatra',
		'suddha_jadhagam',
		'regional_site',
		'marital_status',
		'mothertongue',
		'country',
		'state',
		'city',
		'zip_code',
		'height',
		'weight',
		'skin_tone',
		'body_type',
		'health_info',
		'blood_group',
		'disablity',
		'smoke',
		'drink',
		'diet',
		'education_level',
		'education_field',
		'working_with',
		'working_as',
		'annual_income',
		'mobile_number',
		'father_status',
		'mother_status',
		'num_of_married_brother',
		'num_of_unmarried_brother',
		'num_of_married_sister',
		'num_of_unmarried_sister',
		'family_type',
		'family_value',
		'affluence_level',
		'grow_up_in',
		'about_me',
		'photo',
		'mob_num_verification',
		'id_proof',
		'register_step',
		'status',
		'last_login',
		'created_by',
		'profile_approval',
		'image_approval',
		'cb',
		'ub',
		'doc',
		'dou',
	),
)); ?>
